# docker-compose.yml
version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: translations_api_app
        volumes:
            - ./:/var/www/html
        ports:
            - "8000:8000"
        depends_on:
            - db
            - redis
        networks:
            - appnet
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - DB_HOST=db
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - REDIS_HOST=redis

    web:
        image: nginx:stable-alpine
        container_name: translations_api_nginx
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html:ro
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - appnet

    db:
        image: postgres:15-alpine
        container_name: translations_db
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_DATABASE}
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - appnet

    redis:
        image: redis:7-alpine
        container_name: translations_redis
        networks:
            - appnet

networks:
    appnet:
        driver: bridge

volumes:
    pgdata:
